// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRDiQlPFFg7Wn_S1IGwF6OzpC8LPNKngs',
    appId: '1:611615759078:web:deecf7ea9d3d9ebfdf7927',
    messagingSenderId: '611615759078',
    projectId: 'untitled1-b681f',
    authDomain: 'untitled1-b681f.firebaseapp.com',
    storageBucket: 'untitled1-b681f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhixDHQVfbmB4ntjxOAM3xL1f7sudvEo8',
    appId: '1:611615759078:android:7f1dd451dbd02bdadf7927',
    messagingSenderId: '611615759078',
    projectId: 'untitled1-b681f',
    storageBucket: 'untitled1-b681f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwkC6E6hrdKlS9EQG10_yxXwDcDuW1s8s',
    appId: '1:611615759078:ios:7cb0ae776d36e524df7927',
    messagingSenderId: '611615759078',
    projectId: 'untitled1-b681f',
    storageBucket: 'untitled1-b681f.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwkC6E6hrdKlS9EQG10_yxXwDcDuW1s8s',
    appId: '1:611615759078:ios:be020f43349bce12df7927',
    messagingSenderId: '611615759078',
    projectId: 'untitled1-b681f',
    storageBucket: 'untitled1-b681f.appspot.com',
    iosBundleId: 'com.example.untitled1.RunnerTests',
  );
}
